### ISSUE TITLE
Win rates calculation for various card sets has a lot of duplicate code duplication

### ISSUE THREAD

**Issue by kontaras** [kontaras/LegendaryStats#71]
There are several instances of copy and pasted code in controllers that share logic for all card set types:

- [https://sonarcloud.io/project/issues?id=knary_LegendaryStats&issues=AXtC4s2BR6tbtusmp4l_&open=AXtC4s2BR6tbtusmp4l_](https://sonarcloud.io/project/issues?id=knary_LegendaryStats&issues=AXtC4s2BR6tbtusmp4l_&open=AXtC4s2BR6tbtusmp4l_)
- https://sonarcloud.io/project/issues?id=knary_LegendaryStats&issues=AXtC4s4OR6tbtusmp4mA&open=AXtC4s4OR6tbtusmp4mA

**Comment by knary** [comment]
I tried several refactorings and could not find an elegant solution.
